services:

  mongodb:
    image: mongo:7
    container_name: hospital-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hospital-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/hospital_management
      JWT_SECRET: super_secret_hospital_jwt_key_2025_secure_and_long
      CLIENT_URL: http://localhost:5173
      DASHBOARD_URL: http://localhost:5174
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hospital-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: hospital-dashboard
    restart: unless-stopped
    ports:
      - "5174:5174"
    depends_on:
      - backend

volumes:
  mongo_data: